services:
  web:
    container_name: cp-albis-motorland # TODO: chang me for new instance
    build: .
    #    image: "traefik/whoami"
    environment:
      SHOPIFY_APP_URL: "https://cp-albis-motorland.cpro-server.de"
      SHOPIFY_SHOP: "cp-albis-motorland.myshopify.com"
      HOST: "0.0.0.0"
      SHOPIFY_API_KEY: "5fefbbc3ee82ed723767a5e9019489e1"
      SHOPIFY_API_SECRET: "da78806dd6514cf8def525790ef16dd2"
      SCOPES: "write_products,write_orders,read_orders"
      DATABASE_URL: "mysql://root:1WrPZqlCnk4CHbpd31cq@cp-albis-motorland_db:3306/cp-albis-motorland" # TODO: change me for new instance
    labels:
      - traefik.enable=true
      - traefik.http.routers.cp-albis-motorland.rule=Host(`cp-albis-motorland.cpro-server.de`) # TODO: change me for new instance
      - traefik.http.routers.cp-albis-motorland.entrypoints=websecure
      - traefik.http.routers.cp-albis-motorland.tls.certresolver=letsencrypt
    #   - traefik.http.services.ebike.loadbalancer.server.port=3000
    restart: unless-stopped
    networks:
      - web
      - intern
  # might be needed, but seems to work without
  #    dns:
  #      - 8.8.8.8
  db:
    container_name: cp-albis-motorland_db # TODO: change me for new instance
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --skip-innodb-read-only-compressed
    image: mariadb:10
    restart: unless-stopped
    volumes:
      - ../databaseData/cp-albis-motorland:/var/lib/mysql # TODO: change me for new instnaces
    environment:
      - MARIADB_INITDB_SKIP_TZINFO=true
        #  - TZ=Europe/Berlin
      - MYSQL_ROOT_PASSWORD=1WrPZqlCnk4CHbpd31cq # TODO: you may change me
    networks:
      - intern

networks:
  web:
    external: true
  intern:
    external: false
