# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "19a3cd83438a8cf1c48c187b5ee9af43"
name = "CP - Albis Leasing"
handle = "cp-albis-motorland"
application_url = "https://cp-albis-motorland.cpro-server.de"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "cp-albisleasing.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_draft_orders,write_orders,write_products"

[auth]
redirect_urls = [
  "https://cp-albis-motorland.cpro-server.de/auth/callback",
  "https://cp-albis-motorland.cpro-server.de/auth/shopify/callback",
  "https://cp-albis-motorland.cpro-server.de/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
